lang_extensions = {
    "py": "python3",
    "cpp": "cpp",
    "c": "c",
    "js": "javascript",
    "java": "java",
    "hs": "haskell",
    "bash": "bash",
    "cr": "crystal",
    "exs": "elixir",
    "d": "d",
    "rb": "ruby",
    "rs": "rust",
    "lisp": "lisp",
    "go": "go",
    "scala": "scala",
    "swift": "swift",
    "ts": "typescript",
    "lua": "lua",
    "nim": "nim",
    "php": "php",
    "pl": "perl",
    "cs": "csharp",
}
